// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinance.Persistence;

#nullable disable

namespace PersonalFinance.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250622063401_SeedCategoryRules")]
    partial class SeedCategoryRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinance.Domain.Entities.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keyword");

                    b.Property<int>("KeywordLength")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_length");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_category_rules");

                    b.ToTable("category_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Keyword = "BI-FAST CR TRANSFER   DR 562 RIKKI H HASIBUAN",
                            KeywordLength = 45,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Keyword = "BI-FAST CR TRANSFER   DR 490 RIKKI H HASIBUAN",
                            KeywordLength = 45,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Keyword = "TRANSFER OUT RIKKI H HASIBUAN 1310013349",
                            KeywordLength = 40,
                            Type = "Saving"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bill",
                            Keyword = "TRANSFER OUT MUHAMMAD IZUDDIN HAN",
                            KeywordLength = 33,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Keyword = "Sent money to Rikki H Hasibuan",
                            KeywordLength = 30,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Keyword = "Transfer dari RIKKI H HASIBUAN",
                            KeywordLength = 30,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 7,
                            Category = "",
                            Keyword = "TRANSFER OUT RIKKI H HASIBUAN",
                            KeywordLength = 29,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 8,
                            Category = "",
                            Keyword = "Transfer ke Rikki H Hasibuan",
                            KeywordLength = 28,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 9,
                            Category = "",
                            Keyword = "TRANSFER IN SYAFTRACO",
                            KeywordLength = 21,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Vet and Dog Supply",
                            Keyword = "Yayasan Bali Rescue",
                            KeywordLength = 19,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Vet and Dog Supply",
                            Keyword = "BERKAT LISAN MULIA",
                            KeywordLength = 18,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Self-Care",
                            Keyword = "KADEK KRISNA CHAND",
                            KeywordLength = 18,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bill",
                            Keyword = "LIDYA EVANGELISTA",
                            KeywordLength = 17,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Vet and Dog Supply",
                            Keyword = "BALI RESCUE DOG",
                            KeywordLength = 15,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Vet and Dog Supply",
                            Keyword = "NI MADE CHRISTA",
                            KeywordLength = 15,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Vet and Dog Supply",
                            Keyword = "Nyoman Sunita",
                            KeywordLength = 13,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Saving Interest",
                            Keyword = "Bunga Didapat",
                            KeywordLength = 13,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Self-Care",
                            Keyword = "Saepul Anwar",
                            KeywordLength = 12,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Housekeeping",
                            Keyword = "Housekeeping",
                            KeywordLength = 12,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Bill",
                            Keyword = "KETUT CATRA",
                            KeywordLength = 11,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Food",
                            Keyword = "Olahan Laut",
                            KeywordLength = 11,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Food",
                            Keyword = "Red Dragon",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Food",
                            Keyword = "Tomoro BNI",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Food",
                            Keyword = "Bakso Solo",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Food",
                            Keyword = "BALE UDANG",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Food",
                            Keyword = "JUICE TIME",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Food",
                            Keyword = "Rumah Maka",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Food",
                            Keyword = "Kedai Kopi",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Food",
                            Keyword = "Kopi Kenan",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Food",
                            Keyword = "Gusto Gela",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Food",
                            Keyword = "BIJI WORLD",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Groceries",
                            Keyword = "NIRMALA BA",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Food",
                            Keyword = "Olahan Lau",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Motor/Car Service",
                            Keyword = "Astra Moto",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Motor/Car Service",
                            Keyword = "Planet Ban",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Workstation",
                            Keyword = "DAPUR PRIM",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Vet and Dog Supply",
                            Keyword = "TIMBUL JAY",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 38,
                            Category = "",
                            Keyword = "transferxx",
                            KeywordLength = 10,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Food",
                            Keyword = "AYAM KREME",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Food",
                            Keyword = "RM ASLI MI",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Groceries",
                            Keyword = "GRANDLUCKY",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Food",
                            Keyword = "WARKOP AGE",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Groceries",
                            Keyword = "Coco Super",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Food",
                            Keyword = "WR WAJAR H",
                            KeywordLength = 10,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Bill",
                            Keyword = "TELKOMSEL",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Food",
                            Keyword = "Dimsum GM",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Food",
                            Keyword = "RM PADANG",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Food",
                            Keyword = "REDDRAGON",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Groceries",
                            Keyword = "LAKSMI UD",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Vet and Dog Supply",
                            Keyword = "Furbabies",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Vet and Dog Supply",
                            Keyword = "EKA PRINT",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Transfer/Admin Fee",
                            Keyword = "Biaya Adm",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Food",
                            Keyword = "UBI BAKAR",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Food",
                            Keyword = "MOTO KOPI",
                            KeywordLength = 9,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Food",
                            Keyword = "MULARASA",
                            KeywordLength = 8,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Saving Interest",
                            Keyword = "INTEREST",
                            KeywordLength = 8,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Bill",
                            Keyword = "BCA CARD",
                            KeywordLength = 8,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Food",
                            Keyword = "Cinnamon",
                            KeywordLength = 8,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Food",
                            Keyword = "WSS BATU",
                            KeywordLength = 8,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Food",
                            Keyword = "Jus Masa",
                            KeywordLength = 8,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Food",
                            Keyword = "MISANTO",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Food",
                            Keyword = "KYOUDAI",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Stock",
                            Keyword = "1310013",
                            KeywordLength = 7,
                            Type = "Saving"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Bill",
                            Keyword = "IZUDDIN",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Bill",
                            Keyword = "Netflix",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Bill",
                            Keyword = "chatGPT",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Withdrawing",
                            Keyword = "Tarikan",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Food",
                            Keyword = "Holland",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Food",
                            Keyword = "KWETIAU",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Transfer/Admin Fee",
                            Keyword = "Charges",
                            KeywordLength = 7,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Food",
                            Keyword = "LAKLAK",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Bill",
                            Keyword = "WIGUNA",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Food",
                            Keyword = "Conato",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Food",
                            Keyword = "Pepito",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Entertainment",
                            Keyword = "PT MNC",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Food",
                            Keyword = "INDOMA",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Food",
                            Keyword = "Es Teh",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Food",
                            Keyword = "Sambal",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Food",
                            Keyword = "WARUNG",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Medical",
                            Keyword = "Klinik",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Clothing",
                            Keyword = "Uniqlo",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Salary",
                            Keyword = "K2FLY",
                            KeywordLength = 5,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 83,
                            Category = "",
                            Keyword = "CRxxx",
                            KeywordLength = 5,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Bill",
                            Keyword = "Bills",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Housekeeping",
                            Keyword = "londri",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Food",
                            Keyword = "Yoyok",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Food",
                            Keyword = "Bubur",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Food",
                            Keyword = "Gohan",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Food",
                            Keyword = "Esteh",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Food",
                            Keyword = "Donut",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Food",
                            Keyword = "BAKMI",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Food",
                            Keyword = "Bakso",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Food",
                            Keyword = "Pempek",
                            KeywordLength = 6,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Tax",
                            Keyword = "Pajak",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Food",
                            Keyword = "Donat",
                            KeywordLength = 5,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 96,
                            Category = "",
                            Keyword = "nelly",
                            KeywordLength = 5,
                            Type = "Fund Switching"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Bill",
                            Keyword = "BPJS",
                            KeywordLength = 4,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Food",
                            Keyword = "Roti",
                            KeywordLength = 4,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Food",
                            Keyword = "Nasi",
                            KeywordLength = 4,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Food",
                            Keyword = "Gogo",
                            KeywordLength = 4,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Groceries",
                            Keyword = "Arys",
                            KeywordLength = 4,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Food",
                            Keyword = "Mie",
                            KeywordLength = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Groceries",
                            Keyword = "ARY",
                            KeywordLength = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Vet and Dog Supply",
                            Keyword = "PET",
                            KeywordLength = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Vet and Dog Supply",
                            Keyword = "VET",
                            KeywordLength = 3,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Transfer/Admin Fee",
                            Keyword = "FEE",
                            KeywordLength = 3,
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("PersonalFinance.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountIdr")
                        .HasColumnType("numeric")
                        .HasColumnName("amount_idr");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("numeric")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("flow");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<string>("Wallet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wallet");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.ToTable("transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
