namespace PersonalFinance.Application.Investments;

public record Archetype(
    string Id,
    string Label,
    string Color,
    string Glyph,
    string Tagline,
    string Thesis,
    int Risk,           // 1–5
    int ReturnScore,    // 1–5
    string TimeHorizon,
    string MaxDD,
    string TargetReturn,
    int MaxPositions,
    string RebalLabel,
    string RebalRule,
    string[] PrimaryTags,
    string[] SecondaryTags,
    string IdxContext
);

public static class ArchetypeCatalog
{
    public static IReadOnlyDictionary<string, Archetype> All { get; } =
        new Dictionary<string, Archetype>
        {
            ["capital-preservation"] = new(
                Id: "capital-preservation",
                Label: "Capital Preservation",
                Color: "#0EA5E9",
                Glyph: "🛡️",
                Tagline: "Protect what you have",
                Thesis: "Minimise drawdowns and preserve purchasing power through low-volatility instruments. Return is secondary to stability.",
                Risk: 1,
                ReturnScore: 1,
                TimeHorizon: "1–3 yr",
                MaxDD: "-5%",
                TargetReturn: "4–7% p.a.",
                MaxPositions: 10,
                RebalLabel: "Quarterly",
                RebalRule: "Rebalance when any asset drifts >3% from target.",
                PrimaryTags: ["bonds", "cash", "gold"],
                SecondaryTags: ["money-market", "T-bills"],
                IdxContext: "Suitable when IHSG P/E > 18 or in bear market. Rotate to IDR deposits and SBN."
            ),
            ["income"] = new(
                Id: "income",
                Label: "Income",
                Color: "#10B981",
                Glyph: "💰",
                Tagline: "Steady cash flow",
                Thesis: "Generate reliable income through dividends, coupons, and distributions. Capital growth is a bonus.",
                Risk: 2,
                ReturnScore: 2,
                TimeHorizon: "3–5 yr",
                MaxDD: "-15%",
                TargetReturn: "8–12% p.a.",
                MaxPositions: 15,
                RebalLabel: "Semi-annual",
                RebalRule: "Reinvest dividends; trim positions >20% above cost basis.",
                PrimaryTags: ["dividend-stocks", "REITs", "bonds"],
                SecondaryTags: ["IDX-30 high-yield", "property-REIT"],
                IdxContext: "Focus on LQ45 high-yield names (BBCA, TLKM, UNVR). Indonesian REITs (DIRE) for property income."
            ),
            ["balanced"] = new(
                Id: "balanced",
                Label: "Balanced / Moderate",
                Color: "#6366F1",
                Glyph: "⚖️",
                Tagline: "Growth with guardrails",
                Thesis: "Equal-weight growth and stability. Mix of equities and fixed income for moderate long-term appreciation with manageable drawdowns.",
                Risk: 3,
                ReturnScore: 3,
                TimeHorizon: "5–7 yr",
                MaxDD: "-25%",
                TargetReturn: "12–18% p.a.",
                MaxPositions: 20,
                RebalLabel: "Annual",
                RebalRule: "Annual rebalance; tactical ±5% equity tilt based on IHSG valuation.",
                PrimaryTags: ["equities", "bonds", "gold"],
                SecondaryTags: ["global-ETF", "IDX composite"],
                IdxContext: "50% IDX blue-chips (BBCA, ASII, BMRI) + 30% government bonds (SBN) + 20% commodity/gold hedge."
            ),
            ["growth"] = new(
                Id: "growth",
                Label: "Growth",
                Color: "#F59E0B",
                Glyph: "📈",
                Tagline: "Long-run wealth building",
                Thesis: "Equity-heavy portfolio targeting long-term capital appreciation. Accepts short-term volatility for higher terminal wealth.",
                Risk: 4,
                ReturnScore: 4,
                TimeHorizon: "7–10 yr",
                MaxDD: "-35%",
                TargetReturn: "18–25% p.a.",
                MaxPositions: 25,
                RebalLabel: "Annual",
                RebalRule: "Let winners run; cut positions below 3% allocation. Rebalance after >40% annual gain.",
                PrimaryTags: ["equities", "growth-stocks", "sectoral"],
                SecondaryTags: ["tech", "consumer", "healthcare"],
                IdxContext: "Overweight IHSG growth sectors: tech (GOTO, BUKA), consumer staples (ICBP, MYOR), healthcare (KLBF)."
            ),
            ["aggressive-growth"] = new(
                Id: "aggressive-growth",
                Label: "Aggressive Growth",
                Color: "#EF4444",
                Glyph: "🚀",
                Tagline: "Maximum long-run upside",
                Thesis: "Concentrated high-conviction bets on transformative companies or sectors. Accepts deep drawdowns for outsized returns.",
                Risk: 5,
                ReturnScore: 5,
                TimeHorizon: "10+ yr",
                MaxDD: "-50%",
                TargetReturn: ">25% p.a.",
                MaxPositions: 15,
                RebalLabel: "Ad hoc",
                RebalRule: "Trim only when a position >30% of portfolio. Hold through volatility.",
                PrimaryTags: ["small-cap", "high-growth", "concentrated"],
                SecondaryTags: ["IPOs", "turnarounds", "thematic"],
                IdxContext: "IDX small-cap growth, new economy stocks. Pair with monitoring of IHSG breadth and foreign net-buy flows."
            ),
            ["global-diversified"] = new(
                Id: "global-diversified",
                Label: "Global Diversified",
                Color: "#8B5CF6",
                Glyph: "🌍",
                Tagline: "Multi-asset, multi-currency",
                Thesis: "Reduce concentration in single country/currency. Geographic and asset-class diversification smooths returns across cycles.",
                Risk: 3,
                ReturnScore: 3,
                TimeHorizon: "5–10 yr",
                MaxDD: "-20%",
                TargetReturn: "10–15% p.a.",
                MaxPositions: 30,
                RebalLabel: "Annual",
                RebalRule: "FX exposure check quarterly; hedge IDR/USD beyond 40% USD allocation.",
                PrimaryTags: ["global-ETF", "USD-assets", "commodities"],
                SecondaryTags: ["S&P500", "MSCI-World", "gold"],
                IdxContext: "Via Bibit/Bareksa global funds or SBN USD. Wise account for direct USD/SGD asset holding."
            ),
            ["crypto-digital"] = new(
                Id: "crypto-digital",
                Label: "Crypto / Digital Assets",
                Color: "#F97316",
                Glyph: "₿",
                Tagline: "High risk, asymmetric upside",
                Thesis: "Small allocation to digital assets for asymmetric return potential. Size to lose 100% without affecting core financial goals.",
                Risk: 5,
                ReturnScore: 5,
                TimeHorizon: "3–7 yr",
                MaxDD: "-80%",
                TargetReturn: "Asymmetric",
                MaxPositions: 10,
                RebalLabel: "Ad hoc",
                RebalRule: "Cap portfolio weight at 10–15%. Take profits at 5× cost into stablecoins.",
                PrimaryTags: ["BTC", "ETH", "DeFi"],
                SecondaryTags: ["stablecoins", "L2", "altcoins"],
                IdxContext: "Regulated via Tokocrypto/Indodax (OJK-licensed). Pair with tax planning for crypto gains under PMK-68."
            ),
            ["esg-thematic"] = new(
                Id: "esg-thematic",
                Label: "ESG / Thematic",
                Color: "#14B8A6",
                Glyph: "🌱",
                Tagline: "Values-aligned investing",
                Thesis: "Align portfolio with environmental, social, and governance criteria or specific macro themes (energy transition, digital infra, healthcare).",
                Risk: 3,
                ReturnScore: 3,
                TimeHorizon: "5–10 yr",
                MaxDD: "-25%",
                TargetReturn: "12–18% p.a.",
                MaxPositions: 20,
                RebalLabel: "Annual",
                RebalRule: "Annual ESG-score review; exit positions failing minimum threshold.",
                PrimaryTags: ["ESG", "renewable-energy", "healthcare"],
                SecondaryTags: ["green-bonds", "impact", "SDG"],
                IdxContext: "IDX ESG Leaders index; BBNI green bonds; PGEO (geothermal). SRI-KEHATI index as benchmark."
            ),
        };
}
