-- PF-AI003: transaction_embeddings table for pgvector semantic search
-- vector(1536) matches OpenAI text-embedding-3-small output dimension.
-- ivfflat index is appropriate for ~thousands of rows; switch to hnsw at ~100k+.

CREATE TABLE transaction_embeddings (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id integer NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    embedding   vector(1536) NOT NULL,
    search_text text NOT NULL,           -- audit trail: what was embedded
    model       text NOT NULL DEFAULT 'text-embedding-3-small',
    created_at  timestamp with time zone DEFAULT now()
);

-- one embedding per transaction (UNIQUE enforces idempotent upsert in the service)
CREATE UNIQUE INDEX ON transaction_embeddings (transaction_id);

-- ivfflat index for cosine distance (<=>). lists=100 is good for up to ~1M rows.
CREATE INDEX ON transaction_embeddings
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
