INSERT INTO category_presets (keyword, category, type, flow, keyword_length, version) VALUES
('TARIKAN ATM', 'Withdrawing', 'Expense', 'DB', 11, 1),
('BIAYA ADMIN', 'Admin Fee', 'Expense', 'DB', 11, 1),
('GOPAY', 'E-Wallet', 'Expense', 'DB', 5, 1),
('OVO', 'E-Wallet', 'Expense', 'DB', 3, 1),
('DANA', 'E-Wallet', 'Expense', 'DB', 4, 1),
('SHOPEE', 'Shopping', 'Expense', 'DB', 6, 1),
('TOKOPEDIA', 'Shopping', 'Expense', 'DB', 9, 1),
('LAZADA', 'Shopping', 'Expense', 'DB', 6, 1),
('GRAB', 'Transportation', 'Expense', 'DB', 4, 1),
('GOJEK', 'Transportation', 'Expense', 'DB', 5, 1),
('INDOMARET', 'Groceries', 'Expense', 'DB', 9, 1),
('ALFAMART', 'Groceries', 'Expense', 'DB', 8, 1),
('PLN', 'Utilities', 'Expense', 'DB', 3, 1),
('TELKOM', 'Utilities', 'Expense', 'DB', 6, 1),
('XL AXIATA', 'Utilities', 'Expense', 'DB', 9, 1),
('INDOSAT', 'Utilities', 'Expense', 'DB', 7, 1),
('BUKALAPAK', 'Shopping', 'Expense', 'DB', 9, 1),
('TRAVELOKA', 'Travel', 'Expense', 'DB', 9, 1),
('TIKET', 'Travel', 'Expense', 'DB', 5, 1),
('NETFLIX', 'Entertainment', 'Expense', 'DB', 7, 1),
('SPOTIFY', 'Entertainment', 'Expense', 'DB', 7, 1),
('TRANSFER', 'Transfer', 'Expense', 'DB', 8, 1),
('STARBUCKS', 'Food & Dining', 'Expense', 'DB', 9, 1),
('MCDONALDS', 'Food & Dining', 'Expense', 'DB', 9, 1),
('KFC', 'Food & Dining', 'Expense', 'DB', 3, 1),
('BURGER KING', 'Food & Dining', 'Expense', 'DB', 11, 1),
('PIZZA HUT', 'Food & Dining', 'Expense', 'DB', 9, 1),
('DOMINOS', 'Food & Dining', 'Expense', 'DB', 7, 1),
('XIN WANG', 'Food & Dining', 'Expense', 'DB', 8, 1),
('KOPI KENANGAN', 'Food & Dining', 'Expense', 'DB', 13, 1),
('JANJI JIWA', 'Food & Dining', 'Expense', 'DB', 10, 1),
('EXCELSO', 'Food & Dining', 'Expense', 'DB', 7, 1),
('SUSHI TEI', 'Food & Dining', 'Expense', 'DB', 9, 1),
('HOKBEN', 'Food & Dining', 'Expense', 'DB', 6, 1),
('YOSHINOYA', 'Food & Dining', 'Expense', 'DB', 9, 1),
('CHATIME', 'Food & Dining', 'Expense', 'DB', 7, 1),
('MIXUE', 'Food & Dining', 'Expense', 'DB', 5, 1),
('MARUGAME', 'Food & Dining', 'Expense', 'DB', 8, 1),
('BREADTALK', 'Food & Dining', 'Expense', 'DB', 9, 1),
('JCO', 'Food & Dining', 'Expense', 'DB', 3, 1),
('MAKO', 'Food & Dining', 'Expense', 'DB', 4, 1),
('KIMUKATSU', 'Food & Dining', 'Expense', 'DB', 9, 1),
('PEPPER LUNCH', 'Food & Dining', 'Expense', 'DB', 12, 1),
('BAKMI GM', 'Food & Dining', 'Expense', 'DB', 8, 1),
('TA WAN', 'Food & Dining', 'Expense', 'DB', 6, 1),
('IMPERIAL KITCHEN', 'Food & Dining', 'Expense', 'DB', 16, 1),
('SOLARIA', 'Food & Dining', 'Expense', 'DB', 7, 1),
('ICHIBAN SUSHI', 'Food & Dining', 'Expense', 'DB', 13, 1),
('CGV', 'Entertainment', 'Expense', 'DB', 3, 1),
('XXI', 'Entertainment', 'Expense', 'DB', 3, 1),
('CINEPOLIS', 'Entertainment', 'Expense', 'DB', 9, 1),
('TIMEZONE', 'Entertainment', 'Expense', 'DB', 8, 1),
('AMAZONE', 'Entertainment', 'Expense', 'DB', 7, 1),
('KAI', 'Transportation', 'Expense', 'DB', 3, 1),
('GARUDA INDONESIA', 'Travel', 'Expense', 'DB', 16, 1),
('LION AIR', 'Travel', 'Expense', 'DB', 8, 1),
('CITILINK', 'Travel', 'Expense', 'DB', 8, 1),
('BATIK AIR', 'Travel', 'Expense', 'DB', 9, 1),
('AIRASIA', 'Travel', 'Expense', 'DB', 7, 1),
('SUPERINDO', 'Groceries', 'Expense', 'DB', 9, 1),
('TRANSMART', 'Groceries', 'Expense', 'DB', 9, 1),
('CARREFOUR', 'Groceries', 'Expense', 'DB', 9, 1),
('LOTTEMART', 'Groceries', 'Expense', 'DB', 9, 1),
('HYPERMART', 'Groceries', 'Expense', 'DB', 9, 1),
('FARMERS MARKET', 'Groceries', 'Expense', 'DB', 14, 1),
('RANCH MARKET', 'Groceries', 'Expense', 'DB', 12, 1),
('PAPAYA', 'Groceries', 'Expense', 'DB', 6, 1),
('MINISO', 'Shopping', 'Expense', 'DB', 6, 1),
('UNIQLO', 'Shopping', 'Expense', 'DB', 6, 1),
('H&M', 'Shopping', 'Expense', 'DB', 3, 1),
('ZARA', 'Shopping', 'Expense', 'DB', 4, 1),
('COTTON ON', 'Shopping', 'Expense', 'DB', 9, 1),
('MATAHARI', 'Shopping', 'Expense', 'DB', 8, 1),
('SOGO', 'Shopping', 'Expense', 'DB', 4, 1),
('SEPHORA', 'Shopping', 'Expense', 'DB', 7, 1),
('SOCIOLLA', 'Shopping', 'Expense', 'DB', 8, 1),
('GUARDIAN', 'Health', 'Expense', 'DB', 8, 1),
('WATSONS', 'Health', 'Expense', 'DB', 7, 1),
('CENTURY', 'Health', 'Expense', 'DB', 7, 1),
('KIMIA FARMA', 'Health', 'Expense', 'DB', 11, 1),
('HALODOC', 'Health', 'Expense', 'DB', 7, 1),
('ALODOKTER', 'Health', 'Expense', 'DB', 9, 1),
('SILOAM', 'Health', 'Expense', 'DB', 6, 1),
('MITRA KELUARGA', 'Health', 'Expense', 'DB', 14, 1),
('HERMINA', 'Health', 'Expense', 'DB', 7, 1),
('PONDOK INDAH', 'Health', 'Expense', 'DB', 12, 1),
('ERHA', 'Health', 'Expense', 'DB', 4, 1),
('BPJS', 'Health', 'Expense', 'DB', 4, 1),
('PDAM', 'Utilities', 'Expense', 'DB', 4, 1),
('BI FAST', 'Transfer', 'Expense', 'DB', 7, 1),
('BIF', 'Transfer', 'Expense', 'DB', 3, 1),
('QRIS', 'E-Wallet', 'Expense', 'DB', 4, 1),
('BUNGA', 'Income', 'Income', 'CR', 5, 1),
('SALARY', 'Income', 'Income', 'CR', 6, 1),
('GAJI', 'Income', 'Income', 'CR', 4, 1),
('PAYROLL', 'Income', 'Income', 'CR', 7, 1),
('CASHBACK', 'Income', 'Income', 'CR', 8, 1),
('REFUND', 'Income', 'Income', 'CR', 6, 1),
('DIVIDEN', 'Investment', 'Income', 'CR', 7, 1),
('REKSA DANA', 'Investment', 'Expense', 'DB', 10, 1),
('SAHAM', 'Investment', 'Expense', 'DB', 5, 1),
('OBLIGASI', 'Investment', 'Expense', 'DB', 8, 1),
('AJAIB', 'Investment', 'Expense', 'DB', 5, 1),
('BAREKSA', 'Investment', 'Expense', 'DB', 7, 1),
('BIBIT', 'Investment', 'Expense', 'DB', 5, 1),
('STOCKBIT', 'Investment', 'Expense', 'DB', 8, 1),
('IPOT', 'Investment', 'Expense', 'DB', 4, 1),
('TOKOCRYPTO', 'Investment', 'Expense', 'DB', 10, 1),
('INDODAX', 'Investment', 'Expense', 'DB', 7, 1),
('PLUANG', 'Investment', 'Expense', 'DB', 6, 1),
('LINKAJA', 'E-Wallet', 'Expense', 'DB', 7, 1),
('ISAKU', 'E-Wallet', 'Expense', 'DB', 5, 1),
('FLIP', 'E-Wallet', 'Expense', 'DB', 4, 1),
('OY', 'E-Wallet', 'Expense', 'DB', 2, 1);
