CREATE TABLE category_presets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    keyword character varying(100) NOT NULL,
    category character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    flow character varying(5) NULL,
    keyword_length integer NOT NULL,
    version integer NOT NULL DEFAULT 1,
    CONSTRAINT pk_category_presets PRIMARY KEY (id)
);

CREATE INDEX idx_category_presets_keyword_length ON category_presets (keyword_length DESC);

ALTER TABLE category_presets ENABLE ROW LEVEL SECURITY;

-- Read-only untuk semua authenticated user. Tidak ada INSERT/UPDATE/DELETE policy.
CREATE POLICY "allow_read_category_presets" ON category_presets
    FOR SELECT USING (true);
