-- Add bank_running_balance to transactions. 
-- This represents the balance provided by the bank at the time of the transaction.
-- It is used as part of a composite key for deduplication to ensure data integrity
-- and to distinguish it from any internal app-calculated balances.
ALTER TABLE transactions ADD COLUMN bank_running_balance numeric;

-- Create uploaded_files table for hashing
CREATE TABLE uploaded_files (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_hash text UNIQUE NOT NULL,
    file_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);
