CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    date timestamp with time zone NOT NULL,
    description character varying(500) NOT NULL,
    remarks character varying(500) NOT NULL,
    flow character varying(5) NOT NULL,
    type character varying(15) NOT NULL,
    category character varying(100) NOT NULL,
    wallet character varying(50) NOT NULL,
    amount_idr numeric NOT NULL,
    currency character varying(10) NOT NULL,
    exchange_rate numeric,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE category_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    keyword character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    category character varying(100) NOT NULL,
    keyword_length integer NOT NULL,
    CONSTRAINT pk_category_rules PRIMARY KEY (id)
);
