INSERT INTO category_presets (keyword, category, type, flow, keyword_length, version) VALUES
-- ── QRIS / QR payments (common BCA description patterns) ────────────────────
('TRANSAKSI DEBIT TGL', 'E-Wallet', 'Expense', 'DB', 19, 1),
('QR 014', 'E-Wallet', 'Expense', 'DB', 6, 1),
('QR 002', 'E-Wallet', 'Expense', 'DB', 6, 1),
('QR 001', 'E-Wallet', 'Expense', 'DB', 6, 1),
('KARTU DEBIT', 'Shopping', 'Expense', 'DB', 11, 1),

-- ── Income / transfer patterns (flow=CR) ───────────────────────────────────
('BI-FAST CR', 'Transfer', 'Income', 'CR', 10, 1),
('BI FAST CR', 'Transfer', 'Income', 'CR', 10, 1),
('TRSF MASUK', 'Transfer', 'Income', 'CR', 11, 1),
('TRANSFER MASUK', 'Transfer', 'Income', 'CR', 14, 1),
('INCOMING TRANSFER', 'Transfer', 'Income', 'CR', 18, 1),
('RECEIVED MONEY', 'Transfer', 'Income', 'CR', 13, 1),
('REFUND', 'Income', 'Income', 'CR', 6, 1),
('CASHBACK', 'Income', 'Income', 'CR', 8, 1),
('BONUS', 'Income', 'Income', 'CR', 5, 1),
('HADIAH', 'Income', 'Income', 'CR', 6, 1),
('TUNJANGAN', 'Income', 'Income', 'CR', 9, 1),
('INSENTIF', 'Income', 'Income', 'CR', 8, 1),

-- ── Food & Dining — extended ────────────────────────────────────────────────
('AZKO', 'Household', 'Expense', 'DB', 4, 1),
('WARUNG', 'Food & Dining', 'Expense', 'DB', 6, 1),
('RESTO', 'Food & Dining', 'Expense', 'DB', 5, 1),
('RESTORAN', 'Food & Dining', 'Expense', 'DB', 8, 1),
('RUMAH MAKAN', 'Food & Dining', 'Expense', 'DB', 11, 1),
('MAKAN', 'Food & Dining', 'Expense', 'DB', 5, 1),
('NASI', 'Food & Dining', 'Expense', 'DB', 4, 1),
('MIE', 'Food & Dining', 'Expense', 'DB', 3, 1),
('BAKSO', 'Food & Dining', 'Expense', 'DB', 5, 1),
('SOTO', 'Food & Dining', 'Expense', 'DB', 4, 1),
('PADANG', 'Food & Dining', 'Expense', 'DB', 6, 1),
('AYAM', 'Food & Dining', 'Expense', 'DB', 4, 1),
('SATE', 'Food & Dining', 'Expense', 'DB', 4, 1),
('MARTABAK', 'Food & Dining', 'Expense', 'DB', 8, 1),
('BUBUR', 'Food & Dining', 'Expense', 'DB', 5, 1),
('PECEL', 'Food & Dining', 'Expense', 'DB', 5, 1),
('KETOPRAK', 'Food & Dining', 'Expense', 'DB', 8, 1),
('GADO-GADO', 'Food & Dining', 'Expense', 'DB', 9, 1),
('SIOMAY', 'Food & Dining', 'Expense', 'DB', 6, 1),
('BATAGOR', 'Food & Dining', 'Expense', 'DB', 7, 1),
('DIMSUM', 'Food & Dining', 'Expense', 'DB', 6, 1),
('RAMEN', 'Food & Dining', 'Expense', 'DB', 5, 1),
('SUSHI', 'Food & Dining', 'Expense', 'DB', 5, 1),
('PIZZA', 'Food & Dining', 'Expense', 'DB', 5, 1),
('BURGER', 'Food & Dining', 'Expense', 'DB', 6, 1),
('FRIED CHICKEN', 'Food & Dining', 'Expense', 'DB', 13, 1),
('CAFE', 'Food & Dining', 'Expense', 'DB', 4, 1),
('COFFEE', 'Food & Dining', 'Expense', 'DB', 6, 1),
('KOPI', 'Food & Dining', 'Expense', 'DB', 4, 1),
('TEH', 'Food & Dining', 'Expense', 'DB', 3, 1),
('BOBA', 'Food & Dining', 'Expense', 'DB', 4, 1),
('BUBBLE TEA', 'Food & Dining', 'Expense', 'DB', 10, 1),
('JOLLIBEE', 'Food & Dining', 'Expense', 'DB', 8, 1),
('WENDY', 'Food & Dining', 'Expense', 'DB', 5, 1),
('POPEYES', 'Food & Dining', 'Expense', 'DB', 7, 1),
('SUBWAY', 'Food & Dining', 'Expense', 'DB', 6, 1),
('PANCAKE', 'Food & Dining', 'Expense', 'DB', 7, 1),
('WAFFLE', 'Food & Dining', 'Expense', 'DB', 6, 1),
('ICE CREAM', 'Food & Dining', 'Expense', 'DB', 9, 1),
('HAPPY COW', 'Food & Dining', 'Expense', 'DB', 9, 1),
('BAKERY', 'Food & Dining', 'Expense', 'DB', 6, 1),
('ROTI', 'Food & Dining', 'Expense', 'DB', 4, 1),
('KAFE', 'Food & Dining', 'Expense', 'DB', 4, 1),
('DEPOT', 'Food & Dining', 'Expense', 'DB', 5, 1),
('KANTIN', 'Food & Dining', 'Expense', 'DB', 6, 1),
('KOPITIAM', 'Food & Dining', 'Expense', 'DB', 8, 1),
('FOODCOURT', 'Food & Dining', 'Expense', 'DB', 9, 1),
('FOOD COURT', 'Food & Dining', 'Expense', 'DB', 10, 1),
('SEAFOOD', 'Food & Dining', 'Expense', 'DB', 7, 1),
('PEKING', 'Food & Dining', 'Expense', 'DB', 6, 1),
('SHABU', 'Food & Dining', 'Expense', 'DB', 5, 1),
('YAKINIKU', 'Food & Dining', 'Expense', 'DB', 8, 1),
('KOREAN BBQ', 'Food & Dining', 'Expense', 'DB', 10, 1),

-- ── Groceries — extended ───────────────────────────────────────────────────
('BORMA', 'Groceries', 'Expense', 'DB', 5, 1),
('HERO', 'Groceries', 'Expense', 'DB', 4, 1),
('GIANT', 'Groceries', 'Expense', 'DB', 5, 1),
('LION SUPER', 'Groceries', 'Expense', 'DB', 10, 1),
('FOOD HALL', 'Groceries', 'Expense', 'DB', 9, 1),
('SAM''S CLUB', 'Groceries', 'Expense', 'DB', 9, 1),
('TOSERBA', 'Groceries', 'Expense', 'DB', 7, 1),
('MINIMARKET', 'Groceries', 'Expense', 'DB', 11, 1),
('SWALAYAN', 'Groceries', 'Expense', 'DB', 8, 1),
('SUPERMARKET', 'Groceries', 'Expense', 'DB', 11, 1),
('PASAR SEGAR', 'Groceries', 'Expense', 'DB', 11, 1),

-- ── Transportation — extended ──────────────────────────────────────────────
('OJEK', 'Transportation', 'Expense', 'DB', 4, 1),
('ANGKOT', 'Transportation', 'Expense', 'DB', 6, 1),
('BUSWAY', 'Transportation', 'Expense', 'DB', 6, 1),
('TRANSJAKARTA', 'Transportation', 'Expense', 'DB', 12, 1),
('MRT', 'Transportation', 'Expense', 'DB', 3, 1),
('LRT', 'Transportation', 'Expense', 'DB', 3, 1),
('COMMUTER', 'Transportation', 'Expense', 'DB', 9, 1),
('PARKIR', 'Transportation', 'Expense', 'DB', 6, 1),
('PARKING', 'Transportation', 'Expense', 'DB', 7, 1),
('BENSIN', 'Transportation', 'Expense', 'DB', 6, 1),
('PERTAMINA', 'Transportation', 'Expense', 'DB', 9, 1),
('SHELL', 'Transportation', 'Expense', 'DB', 5, 1),
('VIVO', 'Transportation', 'Expense', 'DB', 4, 1),
('SPBU', 'Transportation', 'Expense', 'DB', 4, 1),
('BBM', 'Transportation', 'Expense', 'DB', 3, 1),
('TOLL', 'Transportation', 'Expense', 'DB', 4, 1),
('JASA MARGA', 'Transportation', 'Expense', 'DB', 10, 1),
('WASKITA', 'Transportation', 'Expense', 'DB', 7, 1),
('MAXIM', 'Transportation', 'Expense', 'DB', 5, 1),
('INDRIVER', 'Transportation', 'Expense', 'DB', 8, 1),
('TAXI', 'Transportation', 'Expense', 'DB', 4, 1),
('BLUEBIRD', 'Transportation', 'Expense', 'DB', 8, 1),
('EXPRESS', 'Transportation', 'Expense', 'DB', 7, 1),
('GOJEK GOCAR', 'Transportation', 'Expense', 'DB', 11, 1),
('GORIDE', 'Transportation', 'Expense', 'DB', 6, 1),
('GRABCAR', 'Transportation', 'Expense', 'DB', 7, 1),
('GRABIKE', 'Transportation', 'Expense', 'DB', 7, 1),
('GRABTAXI', 'Transportation', 'Expense', 'DB', 8, 1),

-- ── Utilities — extended ──────────────────────────────────────────────────
('SMARTFREN', 'Utilities', 'Expense', 'DB', 9, 1),
('TELKOMSEL', 'Utilities', 'Expense', 'DB', 9, 1),
('AXIS', 'Utilities', 'Expense', 'DB', 4, 1),
('PULSA', 'Utilities', 'Expense', 'DB', 5, 1),
('PAKET DATA', 'Utilities', 'Expense', 'DB', 10, 1),
('INTERNET', 'Utilities', 'Expense', 'DB', 8, 1),
('FIRSTMEDIA', 'Utilities', 'Expense', 'DB', 10, 1),
('INDIHOME', 'Utilities', 'Expense', 'DB', 8, 1),
('BIZNET', 'Utilities', 'Expense', 'DB', 6, 1),
('MYREPUBLIC', 'Utilities', 'Expense', 'DB', 10, 1),
('GAS', 'Utilities', 'Expense', 'DB', 3, 1),
('PGN', 'Utilities', 'Expense', 'DB', 3, 1),
('LISTRIK', 'Utilities', 'Expense', 'DB', 7, 1),
('TOKEN LISTRIK', 'Utilities', 'Expense', 'DB', 13, 1),
('AIR PDAM', 'Utilities', 'Expense', 'DB', 8, 1),
('PAM', 'Utilities', 'Expense', 'DB', 3, 1),
('IURAN', 'Utilities', 'Expense', 'DB', 5, 1),

-- ── Health — extended ─────────────────────────────────────────────────────
('APOTEK', 'Health', 'Expense', 'DB', 6, 1),
('APOTIK', 'Health', 'Expense', 'DB', 6, 1),
('RUMAH SAKIT', 'Health', 'Expense', 'DB', 11, 1),
('KLINIK', 'Health', 'Expense', 'DB', 6, 1),
('PUSKESMAS', 'Health', 'Expense', 'DB', 9, 1),
('DOKTER', 'Health', 'Expense', 'DB', 6, 1),
('DENTIST', 'Health', 'Expense', 'DB', 7, 1),
('DRGS', 'Health', 'Expense', 'DB', 4, 1),
('GYM', 'Health', 'Expense', 'DB', 3, 1),
('FITNESS', 'Health', 'Expense', 'DB', 7, 1),
('ANYTIME', 'Health', 'Expense', 'DB', 7, 1),
('FIT HUB', 'Health', 'Expense', 'DB', 7, 1),
('CELEBRITY FITNESS', 'Health', 'Expense', 'DB', 18, 1),
('GOLD''S GYM', 'Health', 'Expense', 'DB', 9, 1),
('VITAMIN', 'Health', 'Expense', 'DB', 7, 1),
('OBAT', 'Health', 'Expense', 'DB', 4, 1),
('MEDIFARMA', 'Health', 'Expense', 'DB', 9, 1),
('K24', 'Health', 'Expense', 'DB', 3, 1),
('MEDIS', 'Health', 'Expense', 'DB', 5, 1),
('LAB KESEHATAN', 'Health', 'Expense', 'DB', 13, 1),
('PRODIA', 'Health', 'Expense', 'DB', 6, 1),
('PRAMITA', 'Health', 'Expense', 'DB', 7, 1),

-- ── Education ─────────────────────────────────────────────────────────────
('SEKOLAH', 'Education', 'Expense', 'DB', 7, 1),
('SPP', 'Education', 'Expense', 'DB', 3, 1),
('KURSUS', 'Education', 'Expense', 'DB', 6, 1),
('BIMBEL', 'Education', 'Expense', 'DB', 6, 1),
('LES', 'Education', 'Expense', 'DB', 3, 1),
('KAMPUS', 'Education', 'Expense', 'DB', 6, 1),
('UNIVERSITAS', 'Education', 'Expense', 'DB', 11, 1),
('UDEMY', 'Education', 'Expense', 'DB', 5, 1),
('COURSERA', 'Education', 'Expense', 'DB', 8, 1),
('RUANGGURU', 'Education', 'Expense', 'DB', 9, 1),
('ZENIUS', 'Education', 'Expense', 'DB', 6, 1),
('QUIPPER', 'Education', 'Expense', 'DB', 7, 1),
('BUKU', 'Education', 'Expense', 'DB', 4, 1),
('GRAMEDIA', 'Education', 'Expense', 'DB', 8, 1),
('PERIPLUS', 'Education', 'Expense', 'DB', 8, 1),
('TOGAMAS', 'Education', 'Expense', 'DB', 7, 1),

-- ── Shopping — extended ───────────────────────────────────────────────────
('IKEA', 'Shopping', 'Expense', 'DB', 4, 1),
('INFORMA', 'Shopping', 'Expense', 'DB', 7, 1),
('COURTS', 'Shopping', 'Expense', 'DB', 6, 1),
('ELECTRONIC CITY', 'Shopping', 'Expense', 'DB', 15, 1),
('ERAFONE', 'Shopping', 'Expense', 'DB', 7, 1),
('IBOX', 'Shopping', 'Expense', 'DB', 4, 1),
('SAMSUNG', 'Shopping', 'Expense', 'DB', 7, 1),
('OPPO', 'Shopping', 'Expense', 'DB', 4, 1),
('XIAOMI', 'Shopping', 'Expense', 'DB', 6, 1),
('ACE HARDWARE', 'Shopping', 'Expense', 'DB', 12, 1),
('DEPO', 'Shopping', 'Expense', 'DB', 4, 1),
('MATAHARI DEPT', 'Shopping', 'Expense', 'DB', 13, 1),
('METRO', 'Shopping', 'Expense', 'DB', 5, 1),
('SPORT STATION', 'Shopping', 'Expense', 'DB', 13, 1),
('PLANET SPORTS', 'Shopping', 'Expense', 'DB', 13, 1),
('EIGER', 'Shopping', 'Expense', 'DB', 5, 1),
('NILAI', 'Shopping', 'Expense', 'DB', 5, 1),
('TOKO', 'Shopping', 'Expense', 'DB', 4, 1),
('ONLINE SHOP', 'Shopping', 'Expense', 'DB', 11, 1),
('BLIBLI', 'Shopping', 'Expense', 'DB', 6, 1),
('JD.ID', 'Shopping', 'Expense', 'DB', 5, 1),
('ORAMI', 'Shopping', 'Expense', 'DB', 5, 1),
('ZALORA', 'Shopping', 'Expense', 'DB', 6, 1),
('BERRYBENKA', 'Shopping', 'Expense', 'DB', 10, 1),
('SALE', 'Shopping', 'Expense', 'DB', 4, 1),

-- ── Entertainment — extended ─────────────────────────────────────────────
('DISNEY', 'Entertainment', 'Expense', 'DB', 6, 1),
('HBO', 'Entertainment', 'Expense', 'DB', 3, 1),
('YOUTUBE', 'Entertainment', 'Expense', 'DB', 7, 1),
('APPLE', 'Entertainment', 'Expense', 'DB', 5, 1),
('GOOGLE PLAY', 'Entertainment', 'Expense', 'DB', 11, 1),
('STEAM', 'Entertainment', 'Expense', 'DB', 5, 1),
('PLAYSTATION', 'Entertainment', 'Expense', 'DB', 11, 1),
('XBOX', 'Entertainment', 'Expense', 'DB', 4, 1),
('VIDIO', 'Entertainment', 'Expense', 'DB', 5, 1),
('VIU', 'Entertainment', 'Expense', 'DB', 3, 1),
('WETV', 'Entertainment', 'Expense', 'DB', 4, 1),
('IQIYI', 'Entertainment', 'Expense', 'DB', 5, 1),
('GAME', 'Entertainment', 'Expense', 'DB', 4, 1),
('KARAOKE', 'Entertainment', 'Expense', 'DB', 7, 1),
('NAV', 'Entertainment', 'Expense', 'DB', 3, 1),
('JOYSOUND', 'Entertainment', 'Expense', 'DB', 8, 1),
('ESCAPE ROOM', 'Entertainment', 'Expense', 'DB', 11, 1),
('TRAMPOLINE', 'Entertainment', 'Expense', 'DB', 10, 1),
('FUNTASTIC', 'Entertainment', 'Expense', 'DB', 9, 1),
('DUFAN', 'Entertainment', 'Expense', 'DB', 5, 1),
('ANCOL', 'Entertainment', 'Expense', 'DB', 6, 1),
('TRANS STUDIO', 'Entertainment', 'Expense', 'DB', 12, 1),

-- ── Travel — extended ────────────────────────────────────────────────────
('HOTEL', 'Travel', 'Expense', 'DB', 5, 1),
('PENGINAPAN', 'Travel', 'Expense', 'DB', 10, 1),
('VILLA', 'Travel', 'Expense', 'DB', 5, 1),
('RESORT', 'Travel', 'Expense', 'DB', 6, 1),
('AIRY', 'Travel', 'Expense', 'DB', 4, 1),
('OYO', 'Travel', 'Expense', 'DB', 3, 1),
('REDDOORZ', 'Travel', 'Expense', 'DB', 8, 1),
('AGODA', 'Travel', 'Expense', 'DB', 5, 1),
('BOOKING', 'Travel', 'Expense', 'DB', 7, 1),
('AIRBNB', 'Travel', 'Expense', 'DB', 6, 1),
('PEGIPEGI', 'Travel', 'Expense', 'DB', 8, 1),
('NUSATRIP', 'Travel', 'Expense', 'DB', 8, 1),
('PELNI', 'Travel', 'Expense', 'DB', 5, 1),
('DAMRI', 'Travel', 'Expense', 'DB', 5, 1),
('PO BUS', 'Travel', 'Expense', 'DB', 6, 1),
('KERETA', 'Travel', 'Expense', 'DB', 6, 1),
('BANDARA', 'Travel', 'Expense', 'DB', 7, 1),
('AIRPORT', 'Travel', 'Expense', 'DB', 7, 1),
('PASSPORT', 'Travel', 'Expense', 'DB', 8, 1),
('VISA', 'Travel', 'Expense', 'DB', 4, 1),

-- ── Investment — extended ────────────────────────────────────────────────
('SBN', 'Investment', 'Expense', 'DB', 3, 1),
('ORI', 'Investment', 'Expense', 'DB', 3, 1),
('SBSN', 'Investment', 'Expense', 'DB', 4, 1),
('SUKUK', 'Investment', 'Expense', 'DB', 5, 1),
('OBLIGASI', 'Investment', 'Expense', 'DB', 8, 1),
('REKSADANA', 'Investment', 'Expense', 'DB', 9, 1),
('CRYPTO', 'Investment', 'Expense', 'DB', 6, 1),
('BITCOIN', 'Investment', 'Expense', 'DB', 7, 1),
('ETHEREUM', 'Investment', 'Expense', 'DB', 8, 1),
('P2P', 'Investment', 'Expense', 'DB', 3, 1),
('FUNDING', 'Investment', 'Expense', 'DB', 7, 1),
('MODALKU', 'Investment', 'Expense', 'DB', 7, 1),
('AMARTHA', 'Investment', 'Expense', 'DB', 6, 1),
('INVESTASI', 'Investment', 'Expense', 'DB', 9, 1),
('EMAS', 'Investment', 'Expense', 'DB', 4, 1),
('PEGADAIAN', 'Investment', 'Expense', 'DB', 9, 1),
('TABUNGAN EMAS', 'Investment', 'Expense', 'DB', 13, 1),

-- ── E-Wallet — extended ──────────────────────────────────────────────────
('GOPAY LATER', 'E-Wallet', 'Expense', 'DB', 11, 1),
('SHOPEEPAY', 'E-Wallet', 'Expense', 'DB', 9, 1),
('SHOPEE PAY', 'E-Wallet', 'Expense', 'DB', 10, 1),
('PAYMENTWALL', 'E-Wallet', 'Expense', 'DB', 11, 1),
('JENIUS', 'E-Wallet', 'Expense', 'DB', 6, 1),
('BRIMO', 'E-Wallet', 'Expense', 'DB', 5, 1),
('LIVIN', 'E-Wallet', 'Expense', 'DB', 5, 1),
('BIMO', 'E-Wallet', 'Expense', 'DB', 4, 1),
('OCTO', 'E-Wallet', 'Expense', 'DB', 4, 1),
('VIRTUAL ACCOUNT', 'E-Wallet', 'Expense', 'DB', 15, 1),
('VA ', 'E-Wallet', 'Expense', 'DB', 3, 1),
('DOKU', 'E-Wallet', 'Expense', 'DB', 4, 1),
('MIDTRANS', 'E-Wallet', 'Expense', 'DB', 8, 1),
('XENDIT', 'E-Wallet', 'Expense', 'DB', 6, 1),
('NICEPAY', 'E-Wallet', 'Expense', 'DB', 7, 1),
('IPAYMU', 'E-Wallet', 'Expense', 'DB', 6, 1),

-- ── Saving / tab ─────────────────────────────────────────────────────────
('TABUNGAN', 'Saving', 'Expense', 'DB', 8, 1),
('AUTODEBET', 'Saving', 'Expense', 'DB', 9, 1),
('AUTO DEBET', 'Saving', 'Expense', 'DB', 10, 1),
('CICILAN', 'Saving', 'Expense', 'DB', 7, 1),
('ANGSURAN', 'Saving', 'Expense', 'DB', 8, 1),

-- ── Admin / bank fees ────────────────────────────────────────────────────
('PROVISI', 'Admin Fee', 'Expense', 'DB', 7, 1),
('MATERAI', 'Admin Fee', 'Expense', 'DB', 7, 1),
('BUNGA PINJAMAN', 'Admin Fee', 'Expense', 'DB', 14, 1),
('PENALTI', 'Admin Fee', 'Expense', 'DB', 7, 1),
('BIAYA', 'Admin Fee', 'Expense', 'DB', 5, 1),
('FEE', 'Admin Fee', 'Expense', 'DB', 3, 1),
('CHARGE', 'Admin Fee', 'Expense', 'DB', 6, 1),
('ADMINISTRASI', 'Admin Fee', 'Expense', 'DB', 12, 1),
('PAJAK', 'Admin Fee', 'Expense', 'DB', 5, 1),
('PPH', 'Admin Fee', 'Expense', 'DB', 3, 1),
('PPN', 'Admin Fee', 'Expense', 'DB', 3, 1),

-- ── Transfer flow=null (both debit and credit) ───────────────────────────
('TRSF', 'Transfer', 'Expense', 'DB', 4, 1),
('TRSF E-BANKING', 'Transfer', 'Expense', 'DB', 14, 1),
('BI FAST', 'Transfer', 'Expense', 'DB', 7, 1),
('RTGS', 'Transfer', 'Expense', 'DB', 4, 1),
('SKN', 'Transfer', 'Expense', 'DB', 3, 1),
('KLIRING', 'Transfer', 'Expense', 'DB', 7, 1),
('SWIFT', 'Transfer', 'Expense', 'DB', 5, 1),
('REMITTANCE', 'Transfer', 'Expense', 'DB', 10, 1),
('SETOR TUNAI', 'Transfer', 'Income', 'CR', 11, 1),
('SETORAN', 'Transfer', 'Income', 'CR', 7, 1);
